spring:
  application:
    name: api-gateway-service
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      routes:

        # Account Service Routes
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/v1/accounts/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20

        # Transaction Service Routes
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/v1/transactions/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20

        # Payment Service Routes
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10

  main:
   web-application-type: REACTIVE

eureka:
  client:
   register-with-eureka: true
   fetch-registry: true
   service-url:
    defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8088

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
