spring:
  application:
    name: api-gateway-service
  data:
    redis:
      host: redis
      port: 6379
  cloud:
    gateway:
      routes:

        # Auth Service Routes
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

        # Account Service Routes
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/v1/accounts/**
          filters:
            - AuthenticationFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20

        # Transaction Service Routes
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/v1/transactions/**
          filters:
            - AuthenticationFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20

        # Payment Service Routes
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - AuthenticationFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

  main:
   web-application-type: REACTIVE

eureka:
  client:
   register-with-eureka: true
   fetch-registry: true
  instance:
    prefer-ip-address: true

server:
  port: 8088

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
